Name-based sockets - module: namestack_priv.h File Reference
namestack_priv.h File Reference
#include <linux/types.h>
#include <linux/socket.h>
#include <net/sock.h>
#include <linux/inname.h>
Data Structures
struct name_stream_sock
Typedefs
typedef void(* query_resolv_cb)(const __u8 *response, int len, void *data)
typedef void(* qualify_cb)(const char *name, void *data)
typedef void(* register_cb)(int result, const char *name, void *data)
Functions
static struct name_stream_sock * name_stream_sk (const struct sock *sk)
int name_af_init (void)
void name_af_exit (void)
int name_send_query (const char *name, query_resolv_cb cb, void *data)
void name_cancel_query (void *data)
int choose_addresses (int *num_v6_addresses, struct in6_addr **v6_addresses, int *num_v4_addresses, __be32 **v4_addresses)
int match_v6_address_to_scope (struct sockaddr_in6 *sin6)
int choose_scope_for_v6_address (struct sockaddr_in6 *sin6)
int name_fully_qualify (const char *name, qualify_cb cb, void *data)
int name_send_registration (const char *name, const struct in6_addr *v6_addresses, int num_v6_addresses, const __be32 *v4_addresses, int num_v4_addresses, register_cb cb, void *data)
void name_delete_registration (const char *name)
int name_cache_init (void)
int name_cache_add (const char *name, struct socket *sock)
void name_cache_delete (const char *name)
void name_cache_free (void)
Typedef Documentation
typedef void(* qualify_cb)(const char *name, void *data)
Definition at line 64 of file namestack_priv.h.
typedef void(* query_resolv_cb)(const __u8 *response, int len, void *data)
Definition at line 35 of file namestack_priv.h.
typedef void(* register_cb)(int result, const char *name, void *data)
Definition at line 66 of file namestack_priv.h.
Function Documentation
int choose_addresses (int * num_v6_addresses, struct in6_addr ** v6_addresses, int * num_v4_addresses, __be32 ** v4_addresses)
Definition at line 64 of file address.c.
References print_ip4addr(), and print_ip6addr().
Referenced by name_register().
{
        struct net *net = &init_net;
        struct net_device *dev;
        int n_v6_addresses = 0;
        int n_v4_addresses = 0;
        struct in6_addr *pv6;
        __be32 *pv4;
        int err;
        /* FIXME: lock net? */
        for_each_netdev(net, dev) {
                if (!(dev->flags & IFF_UP))
                        continue;
                if (dev->flags & IFF_LOOPBACK)
                        continue;
                if (dev->ip6_ptr) {
                        struct inet6_dev *in6 = dev->ip6_ptr;
                        struct inet6_ifaddr *addr;
                        for (addr = in6->addr_list; addr; addr = addr->if_next)
                                n_v6_addresses++;
                }
                if (dev->ip_ptr) {
                        struct in_device *in4 = dev->ip_ptr;
                        struct in_ifaddr *addr;
                        for (addr = in4->ifa_list; addr; addr = addr->ifa_next)
                                n_v4_addresses++;
                }
        }
        err = -ENOMEM;
        if (n_v6_addresses) {
                *v6_addresses = kmalloc(n_v6_addresses *
                                        sizeof(struct inet6_ifaddr),
                                        GFP_ATOMIC);
                if (!*v6_addresses)
                        goto out;
                else
                        *num_v6_addresses = n_v6_addresses;
        }
        else {
                *v6_addresses = NULL;
                *num_v6_addresses = 0;
        }
        if (n_v4_addresses) {
                *v4_addresses = kmalloc(n_v4_addresses *
                                        sizeof(struct in_ifaddr),
                                        GFP_ATOMIC);
                if (!*v4_addresses) {
                        kfree(*v6_addresses);
                        goto out;
                }
                else
                        *num_v4_addresses = n_v4_addresses;
        }
        else {
                *v4_addresses = NULL;
                *num_v4_addresses = 0;
        }
        err = 0;
        pv6 = *v6_addresses;
        pv4 = *v4_addresses;
        for_each_netdev(net, dev) {
                if (!(dev->flags & IFF_UP))
                        continue;
                if (dev->flags & IFF_LOOPBACK)
                        continue;
                printk(KERN_INFO "adding addresses from %s\n", dev->name);
                if (dev->ip6_ptr) {
                        struct inet6_dev *in6 = dev->ip6_ptr;
                        struct inet6_ifaddr *addr;
                        for (addr = in6->addr_list; addr;
                             addr = addr->if_next) {
                                print_ip6addr(&addr->addr);
                                *pv6 = addr->addr;
                                pv6++;
                        }
                }
                if (dev->ip_ptr) {
                        struct in_device *in4 = dev->ip_ptr;
                        struct in_ifaddr *addr;
                        for (addr = in4->ifa_list; addr;
                             addr = addr->ifa_next) {
                                print_ip4addr(&addr->ifa_address);
                                *pv4 = addr->ifa_address;
                                pv4++;
                        }
                }
        }
out:
        return err;
}
int choose_scope_for_v6_address (struct sockaddr_in6 * sin6)
Definition at line 189 of file address.c.
Referenced by name_stream_connect_to_v6_address().
{
        /* FIXME: for now, always picks the first interface with an IPv6
         * address, or the first up interface if that fails.  Should instead:
         * 1. Use the source name's scope ID, if the socket is bound to a local
         *    name and the local name is a link-local address.
         * 2. Allow choosing among multiple possible interfaces.
         */
        struct net *net = &init_net;
        struct net_device *dev;
        /* FIXME: lock net? */
        for_each_netdev(net, dev) {
                if (!(dev->flags & IFF_UP))
                        continue;
                if (dev->flags & IFF_LOOPBACK)
                        continue;
                if (dev->ip6_ptr) {
                        struct inet6_dev *in6 = dev->ip6_ptr;
                        struct inet6_ifaddr *addr;
                        for (addr = in6->addr_list; addr; addr = addr->if_next) {
                                printk(KERN_INFO "using scope id %d for %s\n",
                                       dev->ifindex, dev->name);
                                sin6->sin6_scope_id = dev->ifindex;
                                return 0;
                        }
                }
        }
        /* If no IPv6 address was configured, hope for the best with the first
         * up interface.
         */
        for_each_netdev(net, dev) {
                if (!(dev->flags & IFF_UP))
                        continue;
                if (dev->flags & IFF_LOOPBACK)
                        continue;
                printk(KERN_INFO "using scope id %d for %s\n",
                       dev->ifindex, dev->name);
                sin6->sin6_scope_id = dev->ifindex;
                return 0;
        }
        /* No interface, that'll definitely fail */
        return -ENODEV;
}
int match_v6_address_to_scope (struct sockaddr_in6 * sin6)
Definition at line 161 of file address.c.
Referenced by name_bind_to_fqdn().
{
        struct net *net = &init_net;
        struct net_device *dev;
        /* FIXME: lock net? */
        for_each_netdev(net, dev) {
                if (!(dev->flags & IFF_UP))
                        continue;
                if (dev->flags & IFF_LOOPBACK)
                        continue;
                if (dev->ip6_ptr) {
                        struct inet6_dev *in6 = dev->ip6_ptr;
                        struct inet6_ifaddr *addr;
                        for (addr = in6->addr_list; addr; addr = addr->if_next)
                                if (!memcmp(&addr->addr,
                                    sin6->sin6_addr.s6_addr,
                                    sizeof(addr->addr)))
{
                                        sin6->sin6_scope_id = dev->ifindex;
                                        return 0;
                                }
                }
        }
        return -ENODEV;
}
void name_af_exit (void)
Definition at line 2004 of file af_name.c.
References syn_entry::entry, name_stream_syns, and NAME_SYN_BUCKETS.
Referenced by namestack_exit().
{
        int i;
        proto_unregister(&name_stream_proto);
        proto_unregister(&name_dgram_proto);
        sock_unregister(name_family_ops.family);
        for (i = 0; i < NAME_SYN_BUCKETS; i++)
        {
                struct syn_entry *entry;
                struct hlist_node *node, *next;
                hlist_for_each_entry_safe(entry,
                                          node,
                                          next,
                                          &name_stream_syns[i],
                                          entry)
                {
                        hlist_del(node);
                        kfree(entry);
                }
        }
}
int name_af_init (void)
Definition at line 1987 of file af_name.c.
Referenced by namestack_init().
{
        int rc;
        rc = proto_register(&name_stream_proto, 1);
        if (rc)
                goto out;
        rc = proto_register(&name_dgram_proto, 1);
        if (rc)
                goto out;
        rc = sock_register(&name_family_ops);
out:
        return rc;
}
int name_cache_add (const char * name, struct socket * sock)
Definition at line 73 of file namecache.c.
References __name_cache_find(), name_sock_list::entry, lock_name_cache(), name_hash(), name_sock_list::sock, and unlock_name_cache().
Referenced by name_register().
{
        int err;
        u32 bucket = name_hash(name);
        struct name_sock_list *ptr;
        lock_name_cache();
        ptr = __name_cache_find(name, bucket);
        if (ptr) {
                err = -EALREADY;
                goto out;
        }
        ptr = kmalloc(sizeof(struct name_sock_list), GFP_ATOMIC);
        if (!ptr) {
                err = -ENOMEM;
                goto out;
        }
        ptr->sock = sock;
        INIT_LIST_HEAD(&ptr->entry);
        list_add_tail(&name_cache[bucket].entry, &ptr->entry);
        err = 0;
out:
        unlock_name_cache();
        return err;
}
void name_cache_delete (const char * name)
Definition at line 99 of file namecache.c.
References __name_cache_find(), name_sock_list::entry, lock_name_cache(), name_hash(), and unlock_name_cache().
Referenced by name_register(), and name_stream_release().
{
        u32 bucket = name_hash(name);
        struct name_sock_list *ptr;
        lock_name_cache();
        ptr = __name_cache_find(name, bucket);
        if (ptr) {
                list_del(&ptr->entry);
                kfree(ptr);
        }
        unlock_name_cache();
}
void name_cache_free (void)
Definition at line 113 of file namecache.c.
References name_sock_list::entry, and name_cache_size.
Referenced by namestack_exit().
{
        int i;
        for (i = 0; i < name_cache_size; i++) {
                struct name_sock_list *itr, *next;
                list_for_each_entry_safe(itr, next, &name_cache[i].entry,
                                         entry) {
                        list_del(&itr->entry);
                        kfree(itr);
                }
        }
        kfree(name_cache);
}
int name_cache_init (void)
Definition at line 30 of file namecache.c.
References name_sock_list::entry, name_cache_shift, name_cache_size, and name_sock_list::sock.
Referenced by namestack_init().
{
        int err;
        name_cache_shift = 4;
        name_cache = kmalloc(name_cache_size * sizeof(struct name_sock_list),
                             GFP_ATOMIC);
        if (name_cache) {
                int i;
                for (i = 0; i < name_cache_size; i++) {
                        INIT_LIST_HEAD(&name_cache[i].entry);
                        name_cache[i].sock = NULL;
                }
                err = 0;
        }
        else {
                /* defensive line to protect against a broken caller */
                name_cache_shift = 0;
                err = -ENOMEM;
        }
        return err;
}
void name_cancel_query (void * data)
void name_delete_registration (const char * name)
Definition at line 467 of file main.c.
References daemon_pid, NAME_STACK_REGISTER_DELETE, and namestack_send_message().
Referenced by name_stream_release().
{
        int err;
        if (!daemon_pid) {
                printk(KERN_WARNING "no resolver daemon, unable to send query\n");
                err = -ENOSYS;
        }
        else {
                printk(KERN_INFO "deleting registered name %s\n", name);
                /* FIXME:  who handles retrying in case of failure? */
                err = namestack_send_message(daemon_pid,
                                             NAME_STACK_REGISTER_DELETE,
                                             name, strlen(name) + 1);
        }
}
int name_fully_qualify (const char * name, qualify_cb cb, void * data)
Definition at line 400 of file main.c.
References daemon_pid, NAME_STACK_QUALIFY_QUERY, and namestack_send_message_tracked().
Referenced by name_qualify_and_register().
{
        int err;
        if (!daemon_pid) {
                printk(KERN_WARNING "no resolver daemon, unable to send query\n");
                err = -ENOSYS;
        }
        else {
                printk(KERN_INFO "qualifying %s\n", name);
                /* FIXME:  who handles retrying in case of failure? */
                err = namestack_send_message_tracked(daemon_pid,
                                                     NAME_STACK_QUALIFY_QUERY,
                                                     name, strlen(name) + 1,
                                                     cb, data);
        }
        return err;
}
int name_send_query (const char * name, query_resolv_cb cb, void * data)
Definition at line 381 of file main.c.
References daemon_pid, NAME_STACK_NAME_QUERY, and namestack_send_message_tracked().
Referenced by name_stream_connect().
{
        int err;
        if (!daemon_pid) {
                printk(KERN_WARNING "no resolver daemon, unable to send query\n");
                err = -ENOSYS;
        }
        else {
                printk(KERN_INFO "resolving %s\n", name);
                /* FIXME:  who handles retrying in case of failure? */
                err = namestack_send_message_tracked(daemon_pid,
                                                     NAME_STACK_NAME_QUERY,
                                                     name, strlen(name) + 1,
                                                     cb, data);
        }
        return err;
}
int name_send_registration (const char * name, const struct in6_addr * v6_addresses, int num_v6_addresses, const __be32 * v4_addresses, int num_v4_addresses, register_cb cb, void * data)
Definition at line 419 of file main.c.
References daemon_pid, NAME_STACK_REGISTER_QUERY, and namestack_send_message_tracked().
Referenced by name_register().
{
        int err;
        if (!daemon_pid) {
                printk(KERN_WARNING "no resolver daemon, unable to send query\n");
                err = -ENOSYS;
        }
        else {
                char *payload, *ptr;
                size_t name_len, len;
                printk(KERN_INFO "registering %s\n", name);
                name_len = strlen(name) + 1;
                len = name_len;
                len += sizeof(int) + num_v6_addresses * sizeof(struct in6_addr);
                len += sizeof(int) + num_v4_addresses * sizeof(__be32);
                err = -ENOMEM;
                payload = kmalloc(len, GFP_ATOMIC);
                if (!payload)
                        goto out;
                ptr = payload;
                memcpy(ptr, name, name_len);
                ptr += name_len;
                memcpy(ptr, &num_v6_addresses, sizeof(int));
                ptr += sizeof(int);
                memcpy(ptr, v6_addresses,
                       num_v6_addresses * sizeof(struct in6_addr));
                ptr += num_v6_addresses * sizeof(struct in6_addr);
                memcpy(ptr, &num_v4_addresses, sizeof(int));
                ptr += sizeof(int);
                memcpy(ptr, v4_addresses, num_v4_addresses * sizeof(__be32));
                /* FIXME:  who handles retrying in case of failure? */
                err = namestack_send_message_tracked(daemon_pid,
                                                     NAME_STACK_REGISTER_QUERY,
                                                     payload, len,
                                                     cb, data);
                kfree(payload);
        }
out:
        return err;
}
static struct name_stream_sock* name_stream_sk (const struct sock * sk) [static, read]
Definition at line 25 of file namestack_priv.h.
Referenced by __name_cache_find(), name_alloc_stream_socket(), name_qualify_and_register(), name_qualify_cb(), name_register(), name_register_cb(), name_stream_accept(), name_stream_bind(), name_stream_connect(), name_stream_connect_to_resolved_name(), name_stream_connect_to_v4_address(), name_stream_connect_to_v6_address(), name_stream_getname(), name_stream_listen(), name_stream_query_resolve(), name_stream_recvmsg(), name_stream_release(), and name_stream_sendmsg().
{
        return (struct name_stream_sock *)sk;
}