Name-based sockets - module: namecache.c File Reference
namecache.c File Reference
#include <linux/types.h>
#include <linux/socket.h>
#include <net/sock.h>
#include <linux/jhash.h>
#include <linux/list.h>
#include <linux/inname.h>
#include "namestack_priv.h"
Data Structures
struct name_sock_list
Defines
#define name_cache_size (1 << name_cache_shift)
Functions
static DEFINE_SPINLOCK (name_cache_lock)
static void lock_name_cache (void)
static void unlock_name_cache (void)
int name_cache_init (void)
static u32 name_hash (const char *name)
static struct name_sock_list * __name_cache_find (const char *name, u32 bucket)
int name_cache_add (const char *name, struct socket *sock)
void name_cache_delete (const char *name)
void name_cache_free (void)
Variables
static u32 name_cache_shift
static struct name_sock_list * name_cache
Define Documentation
#define name_cache_size (1 << name_cache_shift)
Definition at line 16 of file namecache.c.
Referenced by name_cache_free(), name_cache_init(), and name_hash().
Function Documentation
static struct name_sock_list* __name_cache_find (const char * name, u32 bucket) [static, read]
Definition at line 59 of file namecache.c.
References name_sock_list::entry, name_stream_sk(), name_stream_sock::sname, and name_sock_list::sock.
Referenced by name_cache_add(), and name_cache_delete().
{
        struct name_sock_list *ptr;
        list_for_each_entry(ptr, &name_cache[bucket].entry, entry) {
                struct sock *sk = ptr->sock->sk;
                struct name_stream_sock *name_sk = name_stream_sk(sk);
                if (!strcmp(name_sk->sname.sname_addr.name, name))
                        return ptr;
        }
        return NULL;
}
static DEFINE_SPINLOCK (name_cache_lock) [static]
static void lock_name_cache (void) [inline, static]
Definition at line 20 of file namecache.c.
Referenced by name_cache_add(), and name_cache_delete().
{
        spin_lock(&name_cache_lock);
}
int name_cache_add (const char * name, struct socket * sock)
Definition at line 73 of file namecache.c.
References __name_cache_find(), name_sock_list::entry, lock_name_cache(), name_hash(), name_sock_list::sock, and unlock_name_cache().
Referenced by name_register().
{
        int err;
        u32 bucket = name_hash(name);
        struct name_sock_list *ptr;
        lock_name_cache();
        ptr = __name_cache_find(name, bucket);
        if (ptr) {
                err = -EALREADY;
                goto out;
        }
        ptr = kmalloc(sizeof(struct name_sock_list), GFP_ATOMIC);
        if (!ptr) {
                err = -ENOMEM;
                goto out;
        }
        ptr->sock = sock;
        INIT_LIST_HEAD(&ptr->entry);
        list_add_tail(&name_cache[bucket].entry, &ptr->entry);
        err = 0;
out:
        unlock_name_cache();
        return err;
}
void name_cache_delete (const char * name)
Definition at line 99 of file namecache.c.
References __name_cache_find(), name_sock_list::entry, lock_name_cache(), name_hash(), and unlock_name_cache().
Referenced by name_register(), and name_stream_release().
{
        u32 bucket = name_hash(name);
        struct name_sock_list *ptr;
        lock_name_cache();
        ptr = __name_cache_find(name, bucket);
        if (ptr) {
                list_del(&ptr->entry);
                kfree(ptr);
        }
        unlock_name_cache();
}
void name_cache_free (void)
Definition at line 113 of file namecache.c.
References name_sock_list::entry, and name_cache_size.
Referenced by namestack_exit().
{
        int i;
        for (i = 0; i < name_cache_size; i++) {
                struct name_sock_list *itr, *next;
                list_for_each_entry_safe(itr, next, &name_cache[i].entry,
                                         entry) {
                        list_del(&itr->entry);
                        kfree(itr);
                }
        }
        kfree(name_cache);
}
int name_cache_init (void)
Definition at line 30 of file namecache.c.
References name_sock_list::entry, name_cache_shift, name_cache_size, and name_sock_list::sock.
Referenced by namestack_init().
{
        int err;
        name_cache_shift = 4;
        name_cache = kmalloc(name_cache_size * sizeof(struct name_sock_list),
                             GFP_ATOMIC);
        if (name_cache) {
                int i;
                for (i = 0; i < name_cache_size; i++) {
                        INIT_LIST_HEAD(&name_cache[i].entry);
                        name_cache[i].sock = NULL;
                }
                err = 0;
        }
        else {
                /* defensive line to protect against a broken caller */
                name_cache_shift = 0;
                err = -ENOMEM;
        }
        return err;
}
static u32 name_hash (const char * name) [inline, static]
Definition at line 54 of file namecache.c.
References name_cache_size.
Referenced by name_cache_add(), and name_cache_delete().
{
        return jhash(name, strlen(name), 0) & (name_cache_size - 1);
}
static void unlock_name_cache (void) [inline, static]
Definition at line 25 of file namecache.c.
Referenced by name_cache_add(), and name_cache_delete().
{
        spin_unlock(&name_cache_lock);
}
Variable Documentation
struct name_sock_list* name_cache [static]
Definition at line 17 of file namecache.c.
u32 name_cache_shift [static]
Definition at line 15 of file namecache.c.
Referenced by name_cache_init().